;;; Generate static profile HTML with SBCL; no external libraries required.
(require :asdf)
(defparameter *root* (uiop:pathname-parent-directory-pathname
                      (uiop:pathname-directory-pathname *load-truename*)))

(defun read-json (text)
  "Read JSON without invoking the Lisp reader on input data."
  (let ((i 0) (size (length text)))
    (labels ((peek () (when (< i size) (char text i)))
             (take () (or (prog1 (peek) (incf i)) (error "Unexpected JSON EOF")))
             (ws () (loop while (and (peek) (find (peek) '(#\Space #\Tab #\Return #\Newline))) do (incf i)))
             (expect (c) (unless (eql (take) c) (error "Expected \"~A\" at ~D" c i)))
             (hex4 () (let ((start i)) (incf i 4) (parse-integer text :start start :end i :radix 16)))
             (jstring ()
               (expect #\")
               (with-output-to-string (out)
                 (loop for c = (take) until (char= c #\") do
                   (cond
                     ((char= c #\\)
                      (write-char
                       (case (take)
                         (#\" #\") (#\\ #\\) (#\/ #\/)
                         (#\b #\Backspace) (#\f #\Page) (#\n #\Newline)
                         (#\r #\Return) (#\t #\Tab)
                         (#\u (let ((code (hex4)))
                                 (when (<= #xd800 code #xdbff)
                                   (expect #\\) (expect #\u)
                                   (let ((low (hex4)))
                                     (unless (<= #xdc00 low #xdfff) (error "Invalid surrogate"))
                                     (setf code (+ #x10000 (ash (- code #xd800) 10) (- low #xdc00)))))
                                 (when (<= #xd800 code #xdfff) (error "Invalid surrogate"))
                                 (or (code-char code) (error "Invalid Unicode"))))
                         (otherwise (error "Invalid JSON escape"))) out))
                     ((< (char-code c) 32) (error "Control character in JSON string"))
                     (t (write-char c out))))))
             (sequence-values (end)
               (ws)
               (if (eql (peek) end) (progn (take) nil)
                   (loop collect (value) into values do (ws)
                         when (eql (peek) end) do (take) and return values
                         do (expect #\,))))
             (literal (word result)
               (loop for c across word do (expect c)) result)
             (number-value ()
               ;; Unused numeric content is represented as a tagged literal.
               (let ((start i))
                 (when (eql (peek) #\-) (take))
                 (if (eql (peek) #\0) (take)
                     (progn
                       (unless (and (peek) (digit-char-p (peek))) (error "Invalid number"))
                       (loop while (and (peek) (digit-char-p (peek))) do (take))))
                 (when (eql (peek) #\.)
                   (take)
                   (unless (and (peek) (digit-char-p (peek))) (error "Invalid fraction"))
                   (loop while (and (peek) (digit-char-p (peek))) do (take)))
                 (when (and (peek) (find (peek) "eE"))
                   (take)
                   (when (and (peek) (find (peek) "+-")) (take))
                   (unless (and (peek) (digit-char-p (peek))) (error "Invalid exponent"))
                   (loop while (and (peek) (digit-char-p (peek))) do (take)))
                 (list :number (subseq text start i))))
             (value ()
               (ws)
               (case (peek)
                 (#\" (jstring))
                 (#\{ (take)
                       (let ((obj (make-hash-table :test 'equal)))
                         (ws)
                         (unless (eql (peek) #\})
                           (loop (ws)
                                 (let ((key (jstring)))
                                   (ws) (expect #\:) (setf (gethash key obj) (value)))
                                 (ws)
                                 (when (eql (peek) #\}) (return))
                                 (expect #\,)))
                         (expect #\}) obj))
                 (#\[ (take) (coerce (sequence-values #\]) 'vector))
                 (#\t (literal "true" :true))
                 (#\f (literal "false" :false))
                 (#\n (literal "null" :null))
                 (otherwise (number-value)))))
      (prog1 (value) (ws) (unless (= i size) (error "Trailing JSON input"))))))

(defun object (&rest pairs)
  (let ((obj (make-hash-table :test 'equal)))
    (loop for (key value) on pairs by #'cddr do (setf (gethash key obj) value)) obj))
(defun json-text (value)
  (with-output-to-string (out)
    (labels ((emit (v)
               (typecase v
                 (string (write-char #\" out)
                         (loop for c across v do
                           (case c
                             (#\" (write-string "\\\"" out))
                             (#\\ (write-string "\\\\" out))
                             (#\< (write-string "\\u003c" out))
                             (otherwise (if (< (char-code c) 32)
                                            (format out "\\u~4,'0X" (char-code c))
                                            (write-char c out)))))
                         (write-char #\" out))
                 (hash-table (write-char #\{ out)
                             (let ((first t))
                               (maphash (lambda (k val)
                                          (unless first (write-char #\, out))
                                          (setf first nil) (emit k) (write-char #\: out) (emit val)) v))
                             (write-char #\} out))
                 (vector (write-char #\[ out)
                         (loop for item across v for i from 0 do
                           (unless (zerop i) (write-char #\, out)) (emit item))
                         (write-char #\] out))
                 (otherwise (error "Unsupported JSON output: \"~A\"" v)))))
      (emit value))))
(defun html-escape (text)
  (with-output-to-string (out)
    (loop for c across text do
      (write-string (case c (#\& "&amp;") (#\< "&lt;") (#\> "&gt;")
                         (#\" "&quot;") (#\' "&#x27;") (otherwise (string c))) out))))
(defun join-text (strings separator)
  (format nil "~{~A~}" (loop for s in strings for first = t then nil
                              unless first collect separator collect s)))
(defun replace-between (html start end value)
  (let* ((a (search start html))
         (b (and a (search end html :start2 (+ a (length start))))))
    (unless (and a b (not (search start html :start2 (+ a (length start)))))
      (error "Expected one complete block: ~A" start))
    (concatenate 'string (subseq html 0 (+ a (length start))) value (subseq html b))))
(defun block-html (html key value)
  (replace-between html (format nil "<!-- generated:~A -->" key)
                   (format nil "<!-- /generated:~A -->" key) (format nil "~%~A~%" value)))
(defun field-html (html id value)
  (let* ((marker (format nil "id=\"~A\"" id)) (at (search marker html)))
    (unless at (error "Missing field ~A" id))
    (let* ((start (position #\< html :end at :from-end t))
           (tag-end (position #\Space html :start start))
           (open-end (position #\> html :start at))
           (tag (subseq html (1+ start) tag-end)))
      (replace-between html (subseq html start (1+ open-end)) (format nil "</~A>" tag) value))))
(defun read-file (name) (uiop:read-file-string (merge-pathnames name *root*) :external-format :utf-8))
(defun write-file (name text)
  (with-open-file (out (merge-pathnames name *root*) :direction :output
                       :if-exists :supersede :external-format :utf-8)
    (write-string text out)))
(defun get-in (data &rest keys) (reduce (lambda (obj key) (gethash key obj)) keys :initial-value data))

(let* ((content (read-json (read-file "content.json")))
       (identity (gethash "identity" content))
       (social (coerce (get-in content "terminal" "socialLinks") 'list))
       (base (gethash "url" identity))
       (person (object "@type" "Person" "@id" (concatenate 'string base "#person")
                       "name" (gethash "name" identity) "alternateName" (gethash "alternateNames" identity)
                       "url" base "description" (gethash "description" identity)
                       "sameAs" (coerce (remove-duplicates
                         (loop for link in social unless (equal (gethash "identity" link) "related")
                               collect (gethash "url" link)) :test #'equal :from-end t) 'vector))))
  (dolist (link social)
    (let ((url (gethash "url" link)))
      (unless (or (uiop:string-prefix-p "https://" url) (uiop:string-prefix-p "http://" url))
        (error "Invalid profile URL: ~A" url))))
  (dolist (page '("index.html" "about/index.html"))
    (let* ((home (equal page "index.html")) (html (read-file page))
           (url (if home base (concatenate 'string base "about/")))
           (title (format nil "~A~A（ながせひろみち / hiromichi-ngs）| hrmc.ngs.computer"
                          (if home "" "About | ") (gethash "name" identity)))
           (structured (object "@context" "https://schema.org" "@type" "ProfilePage"
                               "@id" (concatenate 'string url "#profile") "url" url "name" title "mainEntity" person)))
      (setf html (replace-between html "<title>" "</title>" (html-escape title)))
      (setf html (block-html html "seo"
        (with-output-to-string (out)
          (format out "  <meta name=\"~A\" content=\"~A\">~%" "description" (html-escape (gethash "description" identity)))
          (format out "  <link rel=\"~A\" href=\"~A\">~%" "canonical" (html-escape url))
          (loop for (key value) in (list (list "og:type" "profile") (list "og:title" title)
                                        (list "og:description" (gethash "description" identity)) (list "og:url" url))
                do (format out "  <meta property=\"~A\" content=\"~A\">~%" key (html-escape value)))
          (format out "  <script type=\"~A\">~%~A~%  </script>" "application/ld+json" (json-text structured)))))
      (setf html (block-html html "identity"
        (format nil "<p class=\"~A\">~A（~A）<br>Web・Minecraft Modを制作しています。</p>"
                "profile-aliases" (html-escape (gethash "name" identity))
                (html-escape (join-text (coerce (gethash "alternateNames" identity) 'list) " / ")))))
      (if home
          (progn
            (dolist (key '("tag" "title" "sub"))
              (setf html (field-html html (concatenate 'string "hero-" key) (html-escape (get-in content "hero" key)))))
            (setf html (field-html html "links-group-name" (html-escape (get-in content "links" "groupName"))))
            (setf html (field-html html "links-notice" (html-escape (get-in content "links" "notice")))))
          (progn
            (dolist (key '("label" "name" "handle"))
              (setf html (field-html html (concatenate 'string "profile-" key) (html-escape (get-in content "profile" key)))))
            (setf html (field-html html "profile-bio" (join-text (map 'list #'html-escape (get-in content "profile" "bio")) "<br>")))))
      (setf html (block-html html "social"
        (with-output-to-string (out)
          (write-line (if home "<div class=\"links-row\" id=\"links-row\">" "<nav aria-label=\"SNS・関連プロフィール\"><ul>") out)
          (dolist (link social)
            (let ((related (equal (gethash "identity" link) "related"))
                  (href (html-escape (gethash "url" link))) (label (html-escape (gethash "label" link))))
              (if home
                  (format out "<a class=\"~A\" href=\"~A\" target=\"~A\" rel=\"~A\">~A</a>~%" "link-card" href "_blank"
                          (if related "noopener noreferrer" "me noopener noreferrer") label)
                  (format out "<li><a href=\"~A\"~A>~A</a></li>~%" href (if related "" " rel=\"me\"") label))))
          (write-string (if home "</div>" "</ul></nav>") out))))
      (write-file page html)))
  (write-file "robots.txt" (format nil "User-agent: *~%Allow: /~%~%Sitemap: ~Asitemap.xml~%" base))
  (write-file "sitemap.xml"
    (with-output-to-string (out)
      (write-line "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" out)
      (write-line "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" out)
      (dolist (suffix '("" "about/" "photos/" "items/"))
        (format out "  <url><loc>~A</loc></url>~%" (html-escape (concatenate 'string base suffix))))
      (write-line "</urlset>" out))))
(format t "Generated profile HTML, robots.txt, and sitemap.xml~%")
